# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: CodeStitchOfficial/Intermediate-Astro-Decap-CMS
  branch: main
  identity_url: https://auth.decapbridge.com/sites/1ea1e8dd-3c54-40d7-bbe1-74af6c8f16f6
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Logo for Decap login page
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Site URL for J.R. Outdoor Solutions
site_url: https://jroutdoorsolutions.com

# Media configuration - organized by content type for better asset management
media_folder: src/assets/images
public_folder: src/assets/images

# Configure media library for better organization
media_library:
  name: uploadcare
  config:
    publicKey: demo
    multiple: false
    tabs: 'file camera url facebook gdrive gphotos dropbox instagram'
    effects: 'crop,rotate,enhance,grayscale'
    imageShrink: '2000x2000'
    previewStep: true
    clearable: true

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "SEO Description", name: "description", widget: "text", required: true, hint: "Brief description for search engines (150-160 characters)" }
      - { label: "Author", name: "author", widget: "string", required: true, default: "J.R. Outdoor Solutions" }
      - { label: "Publish Date", name: "date", widget: "datetime", required: true }
      - { label: "Cover Image", name: "image", widget: "image", required: true, media_folder: "/src/assets/images/blog" }
      - { label: "Image Alt Text", name: "imageAlt", widget: "string", required: true, hint: "Describe the image for accessibility" }
      - { label: "Featured Post", name: "isFeatured", widget: "boolean", default: false, hint: "Show on homepage" }
      - { label: "Content", name: "body", widget: "markdown", required: true }

  - name: "service-areas"
    label: "Service Areas"
    folder: "src/content/service-areas"
    create: true
    slug: "{{slug}}"
    preview_path: "service-areas/{{slug}}"
    fields:
      - { label: "City/Area Name", name: "title", widget: "string", required: true }
      - { label: "SEO Description", name: "description", widget: "text", required: true, hint: "Brief description for search engines (150-160 characters)" }
      - { label: "URL Slug", name: "slug", widget: "string", required: true, hint: "URL-friendly version, e.g. pulaski-tn", pattern: ['^[a-z0-9-]+$', "Must be lowercase letters, numbers, and hyphens only"] }
      - { label: "Header Image", name: "image", widget: "image", required: true, media_folder: "/src/assets/images/service-areas" }
      - { label: "Image Alt Text", name: "imageAlt", widget: "string", required: true, hint: "Describe the image for accessibility" }
      - { label: "Latitude", name: "lat", widget: "number", value_type: "float", step: 0.0001, required: false, hint: "Optional: For map display" }
      - { label: "Longitude", name: "lng", widget: "number", value_type: "float", step: 0.0001, required: false, hint: "Optional: For map display" }
      - { label: "Content", name: "body", widget: "markdown", required: true, hint: "Detailed information about services in this area" }

  - name: "services"
    label: "Services"
    folder: "src/content/services"
    create: true
    slug: "{{slug}}"
    preview_path: "services/{{slug}}"
    fields:
      - { label: "Service Name", name: "title", widget: "string", required: true }
      - { label: "SEO Description", name: "description", widget: "text", required: true, hint: "Brief description for search engines (150-160 characters)" }
      - { label: "URL Slug", name: "slug", widget: "string", required: true, hint: "URL-friendly version, e.g. septic-installation", pattern: ['^[a-z0-9-]+$', "Must be lowercase letters, numbers, and hyphens only"] }
      - { label: "Service Image", name: "image", widget: "image", required: true, media_folder: "/src/assets/images/services" }
      - { label: "Image Alt Text", name: "imageAlt", widget: "string", required: true, hint: "Describe the image for accessibility" }
      - { label: "Service Details", name: "body", widget: "markdown", required: true, hint: "Detailed description of the service, process, and benefits" }
